# Generated by Django 5.0.1 on 2025-12-30 10:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(help_text="Review title", max_length=255)),
                ("content", models.TextField(help_text="Review content")),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Consultant's response to the review",
                        null=True,
                    ),
                ),
                (
                    "response_at",
                    models.DateTimeField(
                        blank=True, help_text="When the consultant responded", null=True
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether the review is publicly visible"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="The completed project being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewee",
                    models.ForeignKey(
                        help_text="The consultant being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="The client who wrote the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reviewee"], name="reviews_reviewe_0d427f_idx"
                    ),
                    models.Index(
                        fields=["reviewer"], name="reviews_reviewe_965d53_idx"
                    ),
                    models.Index(fields=["rating"], name="reviews_rating_17e8a4_idx"),
                    models.Index(
                        fields=["-created_at"], name="reviews_created_6c5dce_idx"
                    ),
                ],
            },
        ),
    ]
