# Generated by Django 5.0.1 on 2026-01-13 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial_categories"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_limit", models.PositiveIntegerField(default=10)),
                ("daily_used", models.PositiveIntegerField(default=0)),
                ("daily_reset_at", models.DateTimeField(blank=True, null=True)),
                ("monthly_limit", models.PositiveIntegerField(default=100)),
                ("monthly_used", models.PositiveIntegerField(default=0)),
                ("monthly_reset_at", models.DateTimeField(blank=True, null=True)),
                ("total_generations", models.PositiveIntegerField(default=0)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_limit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_limits",
            },
        ),
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("scope_generate", "Scope Generation"),
                            ("scope_refine", "Scope Refinement"),
                            ("deliverables", "Deliverables Generation"),
                            ("proposal", "Proposal Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_text",
                    models.TextField(help_text="The input provided by the user"),
                ),
                (
                    "input_language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        default="ar",
                        max_length=2,
                    ),
                ),
                ("output_text", models.TextField(blank=True, null=True)),
                (
                    "output_language",
                    models.CharField(
                        blank=True,
                        choices=[("ar", "Arabic"), ("en", "English")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generations",
                        to="projects.project",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generations",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_generations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "generation_type"],
                        name="ai_generati_user_id_39160b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="ai_generati_status_95ebf7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_generati_created_f81b11_idx"
                    ),
                ],
            },
        ),
    ]
