# Generated by Django 5.0.1 on 2026-01-02 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispute_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("quality_issues", "Quality Issues"),
                            ("incomplete_work", "Incomplete Work"),
                            ("missed_deadline", "Missed Deadline"),
                            ("communication_issues", "Communication Issues"),
                            ("scope_disagreement", "Scope Disagreement"),
                            ("payment_dispute", "Payment Dispute"),
                            ("unresponsive_party", "Unresponsive Party"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the dispute"),
                ),
                (
                    "desired_resolution",
                    models.TextField(
                        blank=True, help_text="What the initiator wants as resolution"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("awaiting_response", "Awaiting Response"),
                            ("in_mediation", "In Mediation"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "disputed_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in dispute", max_digits=10
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_refund_client", "Full Refund to Client"),
                            ("partial_refund_client", "Partial Refund to Client"),
                            ("release_to_consultant", "Release to Consultant"),
                            (
                                "partial_release_consultant",
                                "Partial Release to Consultant",
                            ),
                            ("mutual_agreement", "Mutual Agreement"),
                            ("no_action", "No Action Required"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "resolution_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final resolution amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on the resolution"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for the other party to respond",
                        null=True,
                    ),
                ),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="orders.order",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dispute activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="disputes/evidence/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dispute evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("is_admin_message", models.BooleanField(default=False)),
                (
                    "is_internal_note",
                    models.BooleanField(
                        default=False,
                        help_text="Internal admin notes not visible to parties",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["dispute_number"], name="disputes_di_dispute_c1ecdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status"], name="disputes_di_status_124397_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["order"], name="disputes_di_order_i_949626_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["initiated_by"], name="disputes_di_initiat_156af8_idx"
            ),
        ),
    ]
