# Generated by Django 5.0.1 on 2026-01-02 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_orders", models.BooleanField(default=True)),
                ("email_proposals", models.BooleanField(default=True)),
                ("email_payments", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_disputes", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_system", models.BooleanField(default=True)),
                ("push_orders", models.BooleanField(default=True)),
                ("push_proposals", models.BooleanField(default=True)),
                ("push_payments", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("push_disputes", models.BooleanField(default=True)),
                ("push_reviews", models.BooleanField(default=True)),
                ("push_system", models.BooleanField(default=True)),
                ("sms_payments", models.BooleanField(default=True)),
                ("sms_disputes", models.BooleanField(default=True)),
                ("sms_system", models.BooleanField(default=False)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(max_length=100)),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("order_created", "Order Created"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_started", "Order Started"),
                            ("order_delivered", "Order Delivered"),
                            ("order_completed", "Order Completed"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_revision_requested", "Revision Requested"),
                            ("milestone_submitted", "Milestone Submitted"),
                            ("milestone_approved", "Milestone Approved"),
                            ("milestone_revision", "Milestone Revision Requested"),
                            ("proposal_received", "Proposal Received"),
                            ("proposal_accepted", "Proposal Accepted"),
                            ("proposal_rejected", "Proposal Rejected"),
                            ("project_invitation", "Project Invitation"),
                            ("project_updated", "Project Updated"),
                            ("payment_received", "Payment Received"),
                            ("payment_released", "Payment Released"),
                            ("withdrawal_approved", "Withdrawal Approved"),
                            ("withdrawal_rejected", "Withdrawal Rejected"),
                            ("dispute_opened", "Dispute Opened"),
                            ("dispute_response_needed", "Dispute Response Needed"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("new_message", "New Message"),
                            ("new_review", "New Review"),
                            ("system_announcement", "System Announcement"),
                            ("account_verified", "Account Verified"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_d21e6a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_18a272_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Order Created"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_started", "Order Started"),
                            ("order_delivered", "Order Delivered"),
                            ("order_completed", "Order Completed"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_revision_requested", "Revision Requested"),
                            ("milestone_submitted", "Milestone Submitted"),
                            ("milestone_approved", "Milestone Approved"),
                            ("milestone_revision", "Milestone Revision Requested"),
                            ("proposal_received", "Proposal Received"),
                            ("proposal_accepted", "Proposal Accepted"),
                            ("proposal_rejected", "Proposal Rejected"),
                            ("project_invitation", "Project Invitation"),
                            ("project_updated", "Project Updated"),
                            ("payment_received", "Payment Received"),
                            ("payment_released", "Payment Released"),
                            ("withdrawal_approved", "Withdrawal Approved"),
                            ("withdrawal_rejected", "Withdrawal Rejected"),
                            ("dispute_opened", "Dispute Opened"),
                            ("dispute_response_needed", "Dispute Response Needed"),
                            ("dispute_resolved", "Dispute Resolved"),
                            ("new_message", "New Message"),
                            ("new_review", "New Review"),
                            ("system_announcement", "System Announcement"),
                            ("account_verified", "Account Verified"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("orders", "Orders"),
                            ("proposals", "Proposals"),
                            ("payments", "Payments"),
                            ("messages", "Messages"),
                            ("disputes", "Disputes"),
                            ("reviews", "Reviews"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_ar", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("message_ar", models.TextField(blank=True)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
    ]
