# Generated by Django 5.2.9 on 2025-12-30 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_initial_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        help_text="Consultant's introduction and approach"
                    ),
                ),
                (
                    "proposed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Proposed price in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Estimated duration in days"),
                ),
                ("delivery_date", models.DateField(help_text="Proposed delivery date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        help_text="Current proposal status",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if rejected)",
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the proposal was submitted",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the proposal was reviewed (accepted/rejected)",
                        null=True,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        help_text="The consultant submitting this proposal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this proposal is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "db_table": "proposals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="proposals_status_6b8498_idx"),
                    models.Index(
                        fields=["project"], name="proposals_project_33f1e1_idx"
                    ),
                    models.Index(
                        fields=["consultant"], name="proposals_consult_8f30d2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="proposals_created_6548ee_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "consultant"),
                        name="unique_proposal_per_consultant_per_project",
                    )
                ],
            },
        ),
    ]
