# Generated by Django 5.0.1 on 2026-01-13 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to the file in storage", max_length=500
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename when uploaded", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to thumbnail for images",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "db_table": "message_attachments",
                "ordering": ["created_at"],
            },
        ),
    ]
