from .scope import SCOPE_GENERATION_SYSTEM, SCOPE_GENERATION_USER, SCOPE_REFINE_SYSTEM, SCOPE_REFINE_USER
from .deliverables import DELIVERABLES_SYSTEM, DELIVERABLES_USER
from .proposal import PROPOSAL_SYSTEM_AR, PROPOSAL_SYSTEM_EN, PROPOSAL_USER_AR, PROPOSAL_USER_EN

__all__ = [
    'SCOPE_GENERATION_SYSTEM',
    'SCOPE_GENERATION_USER',
    'SCOPE_REFINE_SYSTEM',
    'SCOPE_REFINE_USER',
    'DELIVERABLES_SYSTEM',
    'DELIVERABLES_USER',
    'PROPOSAL_SYSTEM_AR',
    'PROPOSAL_SYSTEM_EN',
    'PROPOSAL_USER_AR',
    'PROPOSAL_USER_EN',
]
