# Generated by Django 5.2.9 on 2025-12-28 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual User"),
                            ("organization", "Organization"),
                            ("consultant", "Consultant"),
                            ("admin", "Administrator"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="User Type",
                    ),
                ),
                (
                    "registration_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Is Staff"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Admin Approved"),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Account Status",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("password_reset_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Login At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        default="ar",
                        max_length=5,
                        verbose_name="Preferred Language",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Riyadh", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "consultant_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Consultant"),
                            ("office", "Consulting Office"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Consultant Type",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Full Name / Office Name"
                    ),
                ),
                (
                    "full_name_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Full Name / Office Name (Arabic)",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hourly Rate (SAR)",
                    ),
                ),
                (
                    "saudi_engineering_license_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Saudi Engineering License Number",
                    ),
                ),
                (
                    "license_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/consultants/licenses/",
                        verbose_name="License Document",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(blank=True, default=list, verbose_name="Skills"),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Certifications"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/consultants/",
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "bio_ar",
                    models.TextField(
                        blank=True, null=True, verbose_name="Bio (Arabic)"
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Portfolio URL"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Availability Status",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Reviews"
                    ),
                ),
                (
                    "total_projects_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Projects Completed"
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount Earned",
                    ),
                ),
                (
                    "commercial_registration_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Commercial Registration Number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultant Profile",
                "verbose_name_plural": "Consultant Profiles",
            },
        ),
        migrations.CreateModel(
            name="IndividualProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "full_name_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Full Name (Arabic)",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="National ID"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/individuals/",
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "total_projects_posted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Projects Posted"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount Spent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual Profile",
                "verbose_name_plural": "Individual Profiles",
            },
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
                (
                    "company_name_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Name (Arabic)",
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("engineering_office", "Engineering Office"),
                            ("government", "Government Entity"),
                            ("other", "Other"),
                        ],
                        default="company",
                        max_length=30,
                        verbose_name="Company Type",
                    ),
                ),
                (
                    "commercial_registration_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Commercial Registration Number",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="VAT Number"
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        max_length=255, verbose_name="Representative Name"
                    ),
                ),
                (
                    "representative_position",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Representative Position",
                    ),
                ),
                (
                    "representative_mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Representative Mobile",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/organizations/",
                        verbose_name="Company Logo",
                    ),
                ),
                (
                    "commercial_registration_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/organizations/cr/",
                        verbose_name="Commercial Registration Document",
                    ),
                ),
                (
                    "total_projects_posted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Projects Posted"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Amount Spent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Profile",
                "verbose_name_plural": "Organization Profiles",
            },
        ),
    ]
