# Generated by Django 5.2.9 on 2025-12-28 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve User"),
                            ("suspend", "Suspend User"),
                            ("activate", "Activate User"),
                            ("edit", "Edit User Info"),
                            ("reset_password", "Reset Password"),
                            ("delete", "Delete User"),
                        ],
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Action Details"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin", "created_at"],
                        name="accounts_au_admin_i_7b013b_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="accounts_au_target__1510a0_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_au_action_c683b9_idx",
                    ),
                ],
            },
        ),
    ]
