# Generated by Django 5.2.9 on 2025-12-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("consultant", "Consultant"),
                    ("admin", "Administrator"),
                ],
                default="client",
                max_length=20,
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("organization", "Organization"),
                ],
                default="individual",
                max_length=20,
                verbose_name="User Type",
            ),
        ),
    ]
