# Generated by Django 5.2.9 on 2025-12-30 00:42

from django.db import migrations
import uuid


def create_initial_categories(apps, schema_editor):
    """Create initial engineering project categories"""
    Category = apps.get_model('projects', 'Category')

    categories = [
        {
            'id': uuid.uuid4(),
            'name': 'Electrical Engineering',
            'name_ar': 'الهندسة الكهربائية',
            'description': 'Electrical systems, power distribution, and related projects',
            'icon': 'zap',
            'order': 1,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Mechanical Engineering',
            'name_ar': 'الهندسة الميكانيكية',
            'description': 'Mechanical systems, machinery, and HVAC projects',
            'icon': 'cog',
            'order': 2,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Civil Engineering',
            'name_ar': 'الهندسة المدنية',
            'description': 'Structural, construction, and infrastructure projects',
            'icon': 'building',
            'order': 3,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Instrumentation & Control',
            'name_ar': 'أجهزة القياس والتحكم',
            'description': 'Industrial instrumentation, automation, and control systems',
            'icon': 'gauge',
            'order': 4,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Industrial Automation (Industry 4.0)',
            'name_ar': 'الأتمتة الصناعية (الثورة الصناعية 4.0)',
            'description': 'Smart manufacturing, IoT, and digital transformation projects',
            'icon': 'cpu',
            'order': 5,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Vibration Monitoring & Analysis',
            'name_ar': 'مراقبة وتحليل الاهتزازات',
            'description': 'Predictive maintenance and vibration analysis projects',
            'icon': 'activity',
            'order': 6,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Process Engineering',
            'name_ar': 'هندسة العمليات',
            'description': 'Chemical, petrochemical, and process optimization projects',
            'icon': 'flask-conical',
            'order': 7,
        },
        {
            'id': uuid.uuid4(),
            'name': 'HVAC Systems',
            'name_ar': 'أنظمة التكييف والتبريد',
            'description': 'Heating, ventilation, and air conditioning projects',
            'icon': 'thermometer',
            'order': 8,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Fire & Safety Systems',
            'name_ar': 'أنظمة الحريق والسلامة',
            'description': 'Fire protection, safety systems, and emergency projects',
            'icon': 'flame',
            'order': 9,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Quality Assurance',
            'name_ar': 'ضمان الجودة',
            'description': 'Quality control, testing, and certification projects',
            'icon': 'check-circle',
            'order': 10,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Other',
            'name_ar': 'أخرى',
            'description': 'Other engineering disciplines and specialized projects',
            'icon': 'more-horizontal',
            'order': 99,
        },
    ]

    for cat_data in categories:
        Category.objects.create(**cat_data)


def remove_initial_categories(apps, schema_editor):
    """Remove initial categories (reverse migration)"""
    Category = apps.get_model('projects', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
