# Generated by Django 5.0.1 on 2026-01-13 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anthropic_api_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted Anthropic API key for Claude AI",
                    ),
                ),
                (
                    "ai_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable AI features platform-wide",
                    ),
                ),
                (
                    "ai_daily_limit_per_user",
                    models.PositiveIntegerField(
                        default=10, help_text="Daily AI generation limit per user"
                    ),
                ),
                (
                    "ai_monthly_limit_per_user",
                    models.PositiveIntegerField(
                        default=100, help_text="Monthly AI generation limit per user"
                    ),
                ),
                (
                    "tap_secret_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted Tap Payment secret key",
                    ),
                ),
                (
                    "tap_public_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tap Payment public key",
                        max_length=255,
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Platform fee percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, help_text="Enable maintenance mode"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Message to display during maintenance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
                "db_table": "platform_settings",
            },
        ),
    ]
