# Generated by Django 5.2.9 on 2026-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="claude_model",
            field=models.CharField(
                choices=[
                    (
                        "claude-opus-4-5-20251101",
                        "Claude Opus 4.5 - Premium (Most Intelligent)",
                    ),
                    (
                        "claude-sonnet-4-5-20250929",
                        "Claude Sonnet 4.5 - Smart (Best Balance)",
                    ),
                    (
                        "claude-haiku-4-5-20251001",
                        "Claude Haiku 4.5 - Fast (Most Efficient)",
                    ),
                    ("claude-opus-4-1-20250805", "Claude Opus 4.1 (Legacy)"),
                    ("claude-sonnet-4-20250514", "Claude Sonnet 4 (Legacy)"),
                    ("claude-opus-4-20250514", "Claude Opus 4 (Legacy)"),
                ],
                default="claude-sonnet-4-5-20250929",
                help_text="Claude model to use for AI features",
                max_length=50,
            ),
        ),
    ]
