# Generated by Django 5.0.1 on 2025-12-30 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial_categories"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total escrow amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform fee amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "consultant_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount consultant will receive (amount - platform_fee)",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("funded", "Funded"),
                            ("held", "Held in Escrow"),
                            ("released", "Released to Consultant"),
                            ("refunded", "Refunded to Client"),
                            ("disputed", "Under Dispute"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current escrow status",
                        max_length=20,
                    ),
                ),
                (
                    "escrow_reference",
                    models.CharField(
                        help_text="Unique escrow reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "funded_at",
                    models.DateTimeField(
                        blank=True, help_text="When the escrow was funded", null=True
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When funds were released to consultant",
                        null=True,
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When funds were refunded to client",
                        null=True,
                    ),
                ),
                (
                    "release_note",
                    models.TextField(
                        blank=True, help_text="Note when releasing payment", null=True
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True, help_text="Reason for refund", null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who funds the escrow",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows_as_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        help_text="Consultant who receives the payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows_as_consultant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this escrow is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows",
                        to="projects.project",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Accepted proposal for this escrow",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrows",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escrow",
                "verbose_name_plural": "Escrows",
                "db_table": "escrows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("escrow_hold", "Escrow Hold"),
                            ("escrow_release", "Escrow Release"),
                            ("refund", "Refund"),
                            ("platform_fee", "Platform Fee"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Current transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mada", "Mada"),
                            ("apple_pay", "Apple Pay"),
                            ("stc_pay", "STC Pay"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment gateway",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response from payment gateway",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Transaction description", null=True
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique reference number for the transaction",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the transaction was completed",
                        null=True,
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related escrow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.escrow",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        help_text="User receiving the payment (null for platform fees)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        help_text="User making the payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="projects.project",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        default="Tashawer Platform",
                        help_text="Entity issuing the invoice",
                        max_length=255,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice number", max_length=50, unique=True
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("client_payment", "Client Payment"),
                            ("consultant_payout", "Consultant Payout"),
                            ("platform_fee", "Platform Fee"),
                        ],
                        help_text="Type of invoice",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current invoice status",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, help_text="Subtotal before VAT", max_digits=12
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="VAT percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="VAT amount", max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount including VAT",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Invoice description/notes", null=True
                    ),
                ),
                (
                    "line_items",
                    models.JSONField(default=list, help_text="Invoice line items"),
                ),
                ("issue_date", models.DateField(help_text="Date invoice was issued")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="Date payment was received", null=True
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF invoice",
                        null=True,
                        upload_to="invoices/",
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related escrow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="payments.escrow",
                    ),
                ),
                (
                    "issued_to",
                    models.ForeignKey(
                        help_text="User the invoice is issued to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="payments.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["status"], name="escrows_status_7c8985_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["client"], name="escrows_client__894aab_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["consultant"], name="escrows_consult_0ac959_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(fields=["project"], name="escrows_project_9b8900_idx"),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["escrow_reference"], name="escrows_escrow__0c66c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["-created_at"], name="escrows_created_32c4a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_505a2f_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="transaction_transac_ddda52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["payer"], name="transaction_payer_i_595080_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["payee"], name="transaction_payee_i_15f98c_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference_number"], name="transaction_referen_dda4a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-created_at"], name="transaction_created_cf5536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_status_07776b_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_type"], name="invoices_invoice_bcf470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issued_to"], name="invoices_issued__9a5ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-issue_date"], name="invoices_issue_d_f92197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-created_at"], name="invoices_created_3daf52_idx"
            ),
        ),
    ]
