# Generated by Django 5.0.1 on 2026-01-02 07:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("escrow_hold", "Escrow Hold"),
                    ("escrow_release", "Escrow Release"),
                    ("refund", "Refund"),
                    ("platform_fee", "Platform Fee"),
                ],
                help_text="Type of transaction",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current available balance in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Balance pending clearance in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Wallet currency", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("frozen", "Frozen"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        help_text="Current wallet status",
                        max_length=20,
                    ),
                ),
                (
                    "total_deposited",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount deposited over time",
                        max_digits=12,
                    ),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount withdrawn over time",
                        max_digits=12,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total earnings from projects",
                        max_digits=12,
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total spent on projects",
                        max_digits=12,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Owner of this wallet",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Deposit amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current deposit status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gateway_charge_id",
                    models.CharField(
                        blank=True,
                        help_text="Charge ID from payment gateway",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response from payment gateway",
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique deposit reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the deposit was completed",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Reason for failure if failed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User making the deposit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet to deposit into",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposit",
                "verbose_name_plural": "Deposits",
                "db_table": "deposits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="wallets_user_id_9fb6cf_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["status"], name="wallets_status_5720bd_idx"),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(fields=["wallet"], name="deposits_wallet__404996_idx"),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(fields=["user"], name="deposits_user_id_cdbb89_idx"),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(fields=["status"], name="deposits_status_46b764_idx"),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["reference_number"], name="deposits_referen_0e95a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["gateway_charge_id"], name="deposits_gateway_7493cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["-created_at"], name="deposits_created_a6331d_idx"
            ),
        ),
    ]
