# Generated by Django 5.0.1 on 2026-01-02 12:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_transaction_transaction_type_wallet_deposit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of the bank", max_length=100),
                ),
                (
                    "bank_name_ar",
                    models.CharField(
                        blank=True,
                        help_text="Bank name in Arabic",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        help_text="Name on the bank account", max_length=255
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        help_text="International Bank Account Number", max_length=34
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, help_text="SWIFT/BIC code", max_length=11, null=True
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank account number (if different from IBAN)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this bank account has been verified",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary bank account",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the account was verified", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this bank account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified this account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "bank_accounts",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Withdrawal amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Withdrawal fee (if any)",
                        max_digits=12,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount to be transferred (amount - fee)",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current withdrawal status",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique withdrawal reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank transfer reference number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transfer_receipt",
                    models.FileField(
                        blank=True,
                        help_text="Bank transfer receipt",
                        null=True,
                        upload_to="withdrawals/receipts/",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the withdrawal was reviewed",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if rejected)",
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the withdrawal was approved",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the withdrawal started processing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the withdrawal was completed",
                        null=True,
                    ),
                ),
                (
                    "user_note",
                    models.TextField(blank=True, help_text="Note from user", null=True),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, help_text="Internal admin note", null=True
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="Bank account to receive funds",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="payments.bankaccount",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this withdrawal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting withdrawal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet to withdraw from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal",
                "verbose_name_plural": "Withdrawals",
                "db_table": "withdrawals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["user"], name="bank_accoun_user_id_ac4793_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["iban"], name="bank_accoun_iban_9fb624_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["is_verified"], name="bank_accoun_is_veri_bc8cda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["user"], name="withdrawals_user_id_4acc87_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["wallet"], name="withdrawals_wallet__da49e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["status"], name="withdrawals_status_ddef8f_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["reference_number"], name="withdrawals_referen_9a8dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["-created_at"], name="withdrawals_created_3991d0_idx"
            ),
        ),
    ]
