# Generated by Django 5.0.1 on 2026-01-02 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_bankaccount_withdrawal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("tap", "Tap Payment Gateway"), ("other", "Other")],
                        default="tap",
                        help_text="Source of the webhook",
                        max_length=20,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique event ID from the gateway (for idempotency)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("deposit", "Deposit"),
                            ("refund", "Refund"),
                            ("charge.captured", "Charge Captured"),
                            ("charge.failed", "Charge Failed"),
                            ("charge.cancelled", "Charge Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Type of webhook event",
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Our internal reference number (transaction/deposit)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gateway_charge_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gateway's charge/transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed Successfully"),
                            ("failed", "Processing Failed"),
                            ("ignored", "Ignored (Duplicate/Invalid)"),
                        ],
                        default="received",
                        help_text="Processing status of this webhook",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_status",
                    models.CharField(
                        blank=True,
                        help_text="Status reported by the gateway (e.g., CAPTURED, FAILED)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request headers (sanitized)",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full webhook payload"),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP response status we returned",
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response we sent back to gateway",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of times this webhook was received"
                    ),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a duplicate of a previously processed event",
                    ),
                ),
                (
                    "signature_valid",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the webhook signature was valid",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the webhook sender",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the webhook was received"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the webhook was successfully processed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "db_table": "webhook_logs",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "received_at"],
                        name="webhook_log_source_ec93ff_idx",
                    ),
                    models.Index(
                        fields=["event_id"], name="webhook_log_event_i_41a153_idx"
                    ),
                    models.Index(
                        fields=["status"], name="webhook_log_status_58a1da_idx"
                    ),
                    models.Index(
                        fields=["-received_at"], name="webhook_log_receive_d3ba45_idx"
                    ),
                ],
            },
        ),
    ]
