# Generated by Django 5.0.1 on 2026-01-02 18:24

import apps.orders.models.milestone
import apps.orders.models.order
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0004_add_webhook_log"),
        ("projects", "0002_initial_categories"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=apps.orders.models.order.generate_order_number,
                        help_text="Unique order reference number",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Order title (copied from project)", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Order description/scope"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total order amount in SAR",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(help_text="Expected delivery date"),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "deadline_extended",
                    models.BooleanField(
                        default=False, help_text="Whether deadline was extended"
                    ),
                ),
                (
                    "original_delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Original delivery date (if extended)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("under_review", "Under Review"),
                            ("revision_requested", "Revision Requested"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending_payment",
                        help_text="Current order status",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Overall completion percentage (0-100)"
                    ),
                ),
                (
                    "max_revisions",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Maximum number of revisions allowed"
                    ),
                ),
                (
                    "revisions_used",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of revisions used"
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True, help_text="Notes from client", null=True
                    ),
                ),
                (
                    "consultant_notes",
                    models.TextField(
                        blank=True, help_text="Notes from consultant", null=True
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was confirmed (payment received)",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When work started", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was delivered for review",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the order was completed", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the order was cancelled", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cancellation", null=True
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who cancelled the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client who placed the order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        help_text="The consultant working on the order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultant_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escrow",
                    models.OneToOneField(
                        blank=True,
                        help_text="The escrow holding the funds",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="payments.escrow",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this order is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="projects.project",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        help_text="The accepted proposal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Milestone title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of milestone deliverables",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Order of this milestone (for display)"
                    ),
                ),
                ("due_date", models.DateField(help_text="Milestone due date")),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, help_text="Actual completion date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for Review"),
                            ("revision_requested", "Revision Requested"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current milestone status",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Milestone payment amount (if using milestone payments)",
                        max_digits=12,
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether payment has been released for this milestone",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was released", null=True
                    ),
                ),
                (
                    "client_feedback",
                    models.TextField(
                        blank=True, help_text="Client feedback on milestone", null=True
                    ),
                ),
                (
                    "consultant_notes",
                    models.TextField(
                        blank=True, help_text="Consultant notes on milestone", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the milestone was approved",
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When consultant submitted for review",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this milestone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this milestone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "db_table": "milestones",
                "ordering": ["sequence", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Order Created"),
                            ("confirmed", "Order Confirmed"),
                            ("started", "Work Started"),
                            ("milestone_created", "Milestone Created"),
                            ("milestone_started", "Milestone Started"),
                            ("milestone_submitted", "Milestone Submitted"),
                            ("milestone_approved", "Milestone Approved"),
                            ("milestone_revision", "Revision Requested"),
                            ("milestone_completed", "Milestone Completed"),
                            ("deliverable_uploaded", "Deliverable Uploaded"),
                            ("delivered", "Order Delivered"),
                            ("revision_requested", "Revision Requested"),
                            ("completed", "Order Completed"),
                            ("cancelled", "Order Cancelled"),
                            ("disputed", "Dispute Opened"),
                            ("deadline_extended", "Deadline Extended"),
                            ("message", "Message"),
                            ("note", "Note Added"),
                        ],
                        help_text="Type of activity",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Activity description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this activity occurred"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Activity",
                "verbose_name_plural": "Order Activities",
                "db_table": "order_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to=apps.orders.models.milestone.deliverable_upload_path,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_type",
                    models.CharField(help_text="File MIME type", max_length=100),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title/description of deliverable",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Version number"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Whether this is the final version"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        help_text="The milestone this deliverable belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="orders.milestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliverable",
                "verbose_name_plural": "Deliverables",
                "db_table": "deliverables",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["milestone"], name="deliverable_milesto_e42994_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="deliverable_created_8ac7e7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["client"], name="orders_client__cdfbc6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["consultant"], name="orders_consult_7d02bb_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_created_b25042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["expected_delivery_date"], name="orders_expecte_4311c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["order"], name="milestones_order_i_bcee36_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["status"], name="milestones_status_2abe2f_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["due_date"], name="milestones_due_dat_0436c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["sequence"], name="milestones_sequenc_e3793c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(fields=["order"], name="order_activ_order_i_20468c_idx"),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(
                fields=["activity_type"], name="order_activ_activit_057368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(
                fields=["-created_at"], name="order_activ_created_6b25e1_idx"
            ),
        ),
    ]
